/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import Controller.Materia;
import Controller.MateriaArchivoReader;
import Views.CreditosMaterias;
import controller.Cargar_Archivar;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ListSelectionModel;
import views.tables.ModeloDeTabla;
import views.tables.ModeloDeTabla;
import javax.swing.*;
import javax.swing.ListSelectionModel;
import java.util.stream.Collectors;
import utiles.Utiles;

/**
 *
 * @author James Pinto, Carlos Zumba, Eduardo Moreno
 */
public class SimuladorCreditos extends javax.swing.JFrame {
    private List<Materia> materiasMostradas;
    Cargar_Archivar CH = new Cargar_Archivar();

    /**
     * Creates new form SimuladorCreditos
     */
    public SimuladorCreditos() {
        initComponents();
        cargarCarrera();
        
        txtcredito.setText("20");
        
        // Limpiamos y cargamos ciclos (opción por defecto)
        cbxciclo.removeAllItems();
        cbxciclo.addItem("Seleccione un ciclo");
        for (int i = 1; i <= 9; i++) {
            cbxciclo.addItem(String.valueOf(i));
        }
        cbxciclo.setSelectedIndex(0);
        
        // Configuramos selección múltiple en la tabla
        tblmaterias.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        // Inicializar tabla vacía
        tblmaterias.setModel(new ModeloDeTabla(new ArrayList<>()));

        materiasMostradas = new ArrayList<>();
    }
    
    private void cargarCarrera() {
        cbxcarrera.removeAllItems();
        cbxcarrera.addItem("Seleccione una Carrera");
        for (String carrera : CH.retornInformation("data.carreras")) {
            cbxcarrera.addItem(carrera);
        }
    }
    
    private String obtenerRutaArchivo(String carrera) {
        switch (carrera) {
            case "Computacion":
                return "data.computacion";
            case "Telecomunicaciones":
                return "data.Telecomunicaciones";
            case "Electricidad":
                return "data.Electricidad";
            case "Minas":
                return "data.Minas";
            case "Electromecanica":
                return "data.Electromecanica";
            case "Ingenieria Automotriz":
                return "data.IngenieriaAutomotriz";
            default:
                return null;
        }
    }
    
    private void cargarMaterias() {
        String carrera = (String) cbxcarrera.getSelectedItem();
        String cicloSeleccionado = (String) cbxciclo.getSelectedItem();

        if (cicloSeleccionado == null || cicloSeleccionado.equals("Seleccione un ciclo")) {
            // Limpiar tabla y totales si no hay ciclo válido
            tblmaterias.setModel(new ModeloDeTabla(new ArrayList<>()));
            limpiarTotales();
            return;
        }

        int ciclo;
        try {
            ciclo = Integer.parseInt(cicloSeleccionado);
        } catch (NumberFormatException e) {
            limpiarTotales();
            tblmaterias.setModel(new ModeloDeTabla(new ArrayList<>()));
            return;
        }

        String rutaArchivo = obtenerRutaArchivo(carrera);
        if (rutaArchivo == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una carrera válida.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        MateriaArchivoReader lector = new MateriaArchivoReader();
        List<Materia> listaMaterias = lector.leerMateriasDesdeArchivo(rutaArchivo);

        // Filtrar por ciclo
        List<Materia> materiasFiltradas = new ArrayList<>();
        for (Materia m : listaMaterias) {
            if (m.getCiclo() == ciclo) {
                materiasFiltradas.add(m);
            }
        }

        // Crear y asignar modelo a tabla
        ModeloDeTabla modelo = new ModeloDeTabla(materiasFiltradas);
        tblmaterias.setModel(modelo);

        materiasMostradas = materiasFiltradas;  // lista para otras operaciones
        limpiarTotales();
    }

    private void limpiarTotales() {
        jLabel7.setText("0");
        jLabel8.setText("0.00$");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxcarrera = new javax.swing.JComboBox<>();
        cbxciclo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtcredito = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmaterias = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de Creditos");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Simulador de cálculo para créditos por matricula");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 690, 20);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Programa de Estudio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N
        jPanel1.setLayout(null);

        jLabel2.setText("Carrera:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 30, 50, 20);

        jLabel3.setText("Ciclo:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 70, 40, 20);

        cbxcarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxcarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxcarreraActionPerformed(evt);
            }
        });
        jPanel1.add(cbxcarrera);
        cbxcarrera.setBounds(80, 30, 170, 22);

        cbxciclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxcicloActionPerformed(evt);
            }
        });
        jPanel1.add(cbxciclo);
        cbxciclo.setBounds(80, 70, 170, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 50, 270, 120);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actializar Creditos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N
        jPanel2.setLayout(null);

        jLabel4.setText("Digite el nuevo Valor:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 50, 120, 20);

        txtcredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcreditoActionPerformed(evt);
            }
        });
        jPanel2.add(txtcredito);
        txtcredito.setBounds(170, 50, 64, 22);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(310, 50, 380, 120);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asignaturas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N
        jPanel3.setLayout(null);

        tblmaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblmaterias);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 410, 300);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 180, 430, 330);

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(480, 190, 90, 23);

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(590, 190, 90, 23);

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(550, 470, 72, 23);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor a Pagar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N
        jPanel4.setLayout(null);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Creditos Totales:");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(20, 60, 90, 20);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Total a Pagar:");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(20, 110, 90, 20);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel4.add(jLabel7);
        jLabel7.setBounds(130, 60, 70, 20);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel4.add(jLabel8);
        jLabel8.setBounds(130, 110, 70, 20);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(460, 230, 230, 210);

        jMenu1.setText("Modulos");

        jMenuItem2.setText("Carreras");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Materias");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Creditos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(722, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new Carreras(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new FrmMaterias_Ciclo(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new CreditosMaterias(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void txtcreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcreditoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double valorCredito;
        try {
            valorCredito = Double.parseDouble(txtcredito.getText());
            if (valorCredito <= 0) {
                JOptionPane.showMessageDialog(this, "El valor del crédito debe ser positivo.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese un valor numérico para el crédito.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int[] filasSeleccionadas = tblmaterias.getSelectedRows();

        if (filasSeleccionadas.length == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una o más materias para calcular.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ModeloDeTabla modelo = (ModeloDeTabla) tblmaterias.getModel();
        List<Materia> seleccionadas = new ArrayList<>();

        for (int fila : filasSeleccionadas) {
            seleccionadas.add(modelo.getMateriaAt(fila));
        }

        int totalCreditos = Utiles.sumarCreditos(seleccionadas);
        jLabel7.setText(String.valueOf(totalCreditos));

        double valorTotal = Utiles.sumarValorMaterias(seleccionadas, valorCredito);
        jLabel8.setText(String.format("%.2f", valorTotal)+"$");                                        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbxcarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxcarreraActionPerformed
        // TODO add your handling code here:
        cargarMaterias();
    }//GEN-LAST:event_cbxcarreraActionPerformed

    private void cbxcicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxcicloActionPerformed
        // TODO add your handling code here:
        cargarMaterias();
    }//GEN-LAST:event_cbxcicloActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cargarMaterias();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimuladorCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimuladorCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimuladorCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimuladorCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimuladorCreditos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxcarrera;
    private javax.swing.JComboBox<String> cbxciclo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblmaterias;
    private javax.swing.JTextField txtcredito;
    // End of variables declaration//GEN-END:variables
}
